name = "bridgeworld-lol"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[env.production]
name = "bridgeworld-lol"
compatibility_date = "2024-01-01"

[env.production.vars]
NODE_ENV = "production"
NEXT_PUBLIC_PORTAL_URL = "https://bridgeworld.lol"
